language: cpp

compiler: gcc

env: 
   global:
      # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
      #   via the "travis encrypt" command using the project repo's public key
      - secure: ""
addons:
    coverity_scan:
        project:
            name: FragJage/SimpleSock
        build_command_prepend: "cmake ."
        build_command: "make"
        branch_pattern: coverity_scan
    apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9']

install:
  - export CXX="g++-4.9" CC="gcc-4.9"

script:
  - cmake . -G"Unix Makefiles"
  - make

branches:
  only:
    - coverity_scan
